server:
   port: 8081
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/khuyenmai
      username: root
      password: Akthangga1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
databaseName: khuyenmai
