server:
  port: 8083
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
#server:
#port: 8082
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/sanpham
      username: root
      password: Akthangga1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
# eureka:
#    client:
#       service-url:
# #          default-zone: http://localhost:8761/eureka/
#          defaultZone: https://servergiay.herokuapp.com/eureka
#    instance:
#       hostname: "sanphamservice.herokuapp.com"
databaseName: sanpham
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
