# server:
#    port: 8084
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream
spring:
   datasource:
      url: jdbc:mysql://sql7.freemysqlhosting.net:3306/sql7350403
      username: sql7350403
      password: GnftzE5AL1
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
         format_sql: true
   properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
# eureka:
#    client:
#       service-url:
#          default-zone: http://localhost:8761/eureka/
databaseName: sql7350403
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
