# server:
#    port: 8762
zuul:
   ignored-services: "*"

   routes:
      khuyenmai-service:
         path: /khuyenMai/**
         service-id: khuyenmai-service
         sensitive-headers: Cookie,Set-Cookie
      hinhanh-service:
         path: /hinhAnh/**
         service-id: hinhanh-service
         sensitive-headers: Cookie,Set-Cookie
      sanpham-service:
         path: /sanPham/**
         service-id: sanpham-service
         sensitive-headers: Cookie,Set-Cookie
      hoadon-service:
         path: /hoaDon/**
         service-id: hoadon-service
         sensitive-headers: Cookie,Set-Cookie
      taikhoan-service:
         path: /taiKhoan/**
         service-id: taikhoan-service
         sensitive-headers: Cookie,Set-Cookie
      my-service:
         path: /myService/**
         service-id: my-service
         sensitive-headers: Cookie,Set-Cookie
# Map path to auth service
      auth-service:
         path: /auth/**
         service-id: AUTH-SERVICE
         strip-prefix: false
         sensitive-headers: Cookie,Set-Cookie
spring:
    http:
        multipart:
           maxFileSize: 1048576KB
           maxRequestSize: 1048576KB
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ConnectTimeout:  10000
  ReadTimeout:  10000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
